### ISSUE TITLE
Why do I need the connect method?

### ISSUE THREAD

**Issue by gomin1d** [SparklingComet/java-mojang-api#10]
Why do I need to use the connect method?

What is the difference between:
```java
Mojang mojang = new Mojang().connect();
```
and:
```java
Mojang mojang = new Mojang();
```
The connect method documentation says `Should <strong>always</strong> be called after creating the API object.`, but why?

the method connect does not affect other methods, such as getUUIDOfUsername

Then what is the need for it?

The thing is, right now https://status.mojang.com/check doesn't work  
can i refuse to call the connect method? what are the consequences? at first glance everything seems to work fine  
![image](https://user-images.githubusercontent.com/32991511/136700790-ddb94363-9cf0-477f-ac20-8980fffc3152.png)

**Comment by SparklingComet** [comment]
The connect method does some initialization for the `Mojang` object and checks the status of status.mojang.com.

If it has not been called, the Mojang object has not been initialized properly.

**Comment by gomin1d** [comment]
I looked at the code of the Mojang class. And I don't understand what the real point of getting the `connect` method call is. All it does is get the mojang API status. And why I need it if I'm not interested in status. It doesn't really affect other mojang requests. 

Why I'm asking this, it's because the mojang status has stopped working, check it out for yourself - https://status.mojang.com/check 

Translated with www.DeepL.com/Translator (free version)

**Comment by SparklingComet** [comment]
> the mojang status has stopped working, check it out for yourself - https://status.mojang.com/check

I had not realised that, I’ll make changes to the API.
