### ISSUE TITLE
Eclipse Error

### ISSUE THREAD

**Issue by kreidlerflorett** [SparklingComet/java-mojang-api#2]
Hello!
I get the following error if I use the java-mojang-api in eclipse oxygen.
I imported the project via "Git Repositories". Is there a bug in the API or do I make something wrong?

> Exception in thread "main" java.lang.NullPointerException
> 	at org.shanerx.mojang.Mojang.connect(Mojang.java:62)
> 	at bot.HalloWelt.main(HalloWelt.java:10)
`package bot;

import org.shanerx.mojang.Mojang;

public class HalloWelt
{
   public static void main (String args[])
   {
       System.out.println("Start");
       Mojang api = new Mojang().connect();
   }
}`

Screenshot of eclipse [http://prntscr.com/ja3jlb](url)
I would be very grateful if someone could help me.

**Comment by SparklingComet** [comment]
That was unexpected, it’s probably a bug. I’ll get back to you asap.

**Comment by SparklingComet** [comment]
Fixed in #5 , closing.
