### ISSUE TITLE
Error on Mojang#connect()

### ISSUE THREAD

**Issue by lineargraph** [SparklingComet/java-mojang-api#3]
Upon trying to connect via `Mojang#connect()` I get a NullPointerException. I tracked this down to `Mojang#connect()` expecting https://status.mojang.com/check to return a Json OBJECT while it gives an array with the rough format 
```json
[
   {
     "service": "status"
   },
   {
     "service2": "status"
   }
]
```

**Comment by SparklingComet** [comment]
Apologies for my late reply.
Can you please share the full stacktrace?

**Comment by ineanto** [comment]
I also get an NPE on `Mojang#connect()` i think that's the HashMap initialization ?
![image](https://user-images.githubusercontent.com/31483059/41497803-668ee364-715d-11e8-9f51-6388ba2ae0c3.png)

**Comment by lineargraph** [comment]
@SparklingComet your [`Mojang#connect()`](https://github.com/SparklingComet/java-mojang-api/blob/07e1ffea0a299f17e5224ed0be8e316e7f4c6006/src/main/java/org/shanerx/mojang/Mojang.java#L61) method expects a Jsonobject (via `getJSONObject` which returns `null` if the api returns an array) the following `obj.forEach` causes the `NullPointerException`. i currently dont have a stacktrace ready, but any call to Mojang#connect did this (accross various PCs)

**Comment by SparklingComet** [comment]
@Iddenn submitted a fix, please let me know whether the issue has been solved.

**Comment by lineargraph** [comment]
```java

import org.shanerx.mojang.Mojang;

public class Main {
    public static void main(String[] args) {
        Mojang mojang = new Mojang();
        mojang.connect();
    }
}
```
yields the following error
```st
Exception in thread "main" java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to org.json.simple.JSONObject
	at org.shanerx.mojang.Mojang.getJSONObject(Mojang.java:329)
	at org.shanerx.mojang.Mojang.connect(Mojang.java:59)
```
which caused be the exact same problem as before: `mojang.connect()` expects https://status.mojang.com/check to return a JSONObject, but it returns a JSONArray

**Comment by SparklingComet** [comment]
*Should* be fixed, please report back if you can.

**Comment by SparklingComet** [comment]
Inactive issue, not relevant either way after #12 .
