### ISSUE TITLE
Mojang#getPlayerProfile doesn't respect the given UUID

### ISSUE THREAD

**Issue by lineargraph** [SparklingComet/java-mojang-api#4]
[`Mojang#getPlayerProfile(UUID)`](https://github.com/SparklingComet/java-mojang-api/blob/07e1ffea0a299f17e5224ed0be8e316e7f4c6006/src/main/java/org/shanerx/mojang/Mojang.java#L124) doesn't respect the given UUID in the request URL hence, resulting in a NullPointerException on every call.

**Comment by ineanto** [comment]
This is fixed in the pull request i've made.
